version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongo:
        condition: service_started
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cat/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3