apiVersion: v1
kind: Service
metadata:
  name: flask-inventory
spec:
  selector:
    app: my-app
  ports:
  - port: 5000
    targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
